[workspace]
members = [
  "crates/jellypilot-core",
  "crates/jellypilot-auth",
  "crates/jellypilot-ui",
  "crates/jellypilot-media-server",
  "crates/jellypilot-mpv",
  "crates/jellypilot-session",
  "src-iced",
]
exclude = [
  "crates/media-server-api/emby",
  "crates/media-server-api/jellyfin",
  "experiments/iced-local-video",
  "crates/jellypilot-player",
]
resolver = "2"

[workspace.dependencies]
iced = { git = "https://github.com/hewel/iced.git", rev = "f812ae504989444eb57d9f8669c1ab5a2e326c95", features = ["advanced", "advanced-shaping", "image", "svg", "tokio"] }
iced_runtime = { git = "https://github.com/hewel/iced.git", rev = "f812ae504989444eb57d9f8669c1ab5a2e326c95" }

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/hewel/jellypilot"
rust-version = "1.98"
version = "2.0.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
