[workspace]
members = [
  "crates/jellypilot-core",
  "crates/jellypilot-core-wasm",
  "crates/jellypilot-playback-core",
  "src-tauri",
]
exclude = [
  "src-tauri/media-server-api/emby",
  "src-tauri/media-server-api/jellyfin",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/hewel/jellypilot"
rust-version = "1.85"
version = "1.5.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
