import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { AtomicSchema } from '../schema/schema.js'

export const GENERATED_TYPES_BASENAME = 'atomic-input.d.ts'

export function writeGeneratedTypes(schema: AtomicSchema, outFile: string): string {
  const content = generateProjectTypesContent(schema)
  mkdirSync(dirname(outFile), { recursive: true })
  writeFileSync(outFile, content, 'utf8')
  return content
}

export function checkGeneratedTypes(
  schema: AtomicSchema,
  outFile: string,
): { ok: boolean; expected: string; actual?: string } {
  const expected = generateProjectTypesContent(schema)
  let actual: string | undefined
  try {
    actual = readFileSync(outFile, 'utf8')
  } catch {
    return { ok: false, expected }
  }
  return { ok: actual === expected, expected, actual }
}

export function defaultGeneratedTypesPath(root: string): string {
  return join(root, GENERATED_TYPES_BASENAME)
}

function generateProjectTypesContent(schema: AtomicSchema): string {
  const properties: string[] = []
  for (const [name, family] of schema.families) {
    const valueType = valueUnion(family.tokens, family.native, family.categories)
    properties.push(`  ${JSON.stringify(name)}?: ${valueType}`)
  }
  const breakpointKeys = Object.keys(schema.breakpoints)
    .map((key) => JSON.stringify(key))
    .join(' | ')
  return `/* AUTO-GENERATED by atomic-css generate — do not edit */
/* checksum: ${checksumFor(schema)} */
export interface AtomicInput {
${properties.join('\n')}
  sm?: AtomicInput
  md?: AtomicInput
  lg?: AtomicInput
  xl?: AtomicInput
  '2xl'?: AtomicInput
  hover?: AtomicInput
  focus?: AtomicInput
  'focus-visible'?: AtomicInput
  active?: AtomicInput
  dark?: AtomicInput
  disabled?: AtomicInput
}

export type AtomicBreakpoint = ${breakpointKeys || 'never'}

declare module '@jellypilot/atomic-css' {
  export function atomic(input: AtomicInput): string
}
`
}

function valueUnion(
  tokens: Record<string, string> | undefined,
  native: readonly string[] | undefined,
  categories: readonly string[],
): string {
  const parts: string[] = []
  if (tokens) {
    for (const key of Object.keys(tokens)) {
      parts.push(JSON.stringify(key))
    }
  }
  if (native) {
    for (const key of native) {
      parts.push(JSON.stringify(key))
    }
  }
  if (
    categories.includes('numeric-spacing') ||
    categories.includes('numeric-z') ||
    categories.includes('numeric-opacity')
  ) {
    parts.push('number')
  }
  if (categories.includes('fraction')) {
    parts.push('`${number}/${number}`')
  }
  if (
    categories.includes('arbitrary-shadow') ||
    categories.includes('arbitrary-grid')
  ) {
    parts.push('string')
  } else if (
    categories.includes('arbitrary-length') ||
    categories.includes('arbitrary-number') ||
    categories.includes('arbitrary-color')
  ) {
    if (!categories.includes('token')) {
      parts.push('string')
    }
  }
  if (parts.length === 0) return 'string'
  const seen: Record<string, true> = {}
  const unique: string[] = []
  for (const part of parts) {
    if (seen[part]) continue
    seen[part] = true
    unique.push(part)
  }
  return unique.join(' | ')
}

function checksumFor(schema: AtomicSchema): string {
  const payload = JSON.stringify({
    version: schema.version,
    breakpoints: schema.breakpoints,
    families: [...schema.families.entries()].map(([name, family]) => ({
      name,
      property: family.property,
      cssProperty: family.cssProperty,
      tokens: family.tokens,
      native: family.native,
      categories: family.categories,
    })),
  })
  return createHash('sha256').update(payload).digest('hex').slice(0, 16)
}
