[package]
name = "jellypilot-mpv"
description = "External MPV process control and JSON IPC for JellyPilot"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-channel = "2.5.0"
dirs = "6.0.0"
log = "0.4"
jellypilot-core = { path = "../jellypilot-core" }
jellypilot-media-server = { path = "../jellypilot-media-server" }
jellypilot-session = { path = "../jellypilot-session" }
parking_lot = "0.12.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
which = "8.0.2"

[lints]
workspace = true

[features]
test-utils = []
