import { createSprinkles, defineProperties } from '@vanilla-extract/sprinkles';

import { breakpoints, vars } from './vars.css';

const colors = {
  transparent: 'transparent',
  current: 'currentColor',
  background: vars.color.background,
  brandGlow: vars.color.brandGlow,
  error: vars.color.error,
  errorContainer: vars.color.errorContainer,
  onBackground: vars.color.onBackground,
  onError: vars.color.onError,
  onErrorContainer: vars.color.onErrorContainer,
  onPrimary: vars.color.onPrimary,
  onPrimaryContainer: vars.color.onPrimaryContainer,
  onSecondary: vars.color.onSecondary,
  onSecondaryContainer: vars.color.onSecondaryContainer,
  onSurface: vars.color.onSurface,
  onSurfaceVariant: vars.color.onSurfaceVariant,
  onTertiary: vars.color.onTertiary,
  onTertiaryContainer: vars.color.onTertiaryContainer,
  onWarning: vars.color.onWarning,
  onWarningContainer: vars.color.onWarningContainer,
  outline: vars.color.outline,
  outlineVariant: vars.color.outlineVariant,
  primary: vars.color.primary,
  primaryContainer: vars.color.primaryContainer,
  primaryGradientEnd: vars.color.primaryGradientEnd,
  secondary: vars.color.secondary,
  secondaryContainer: vars.color.secondaryContainer,
  secondaryGradientEnd: vars.color.secondaryGradientEnd,
  surface: vars.color.surface,
  surfaceContainer: vars.color.surfaceContainer,
  surfaceContainerHigh: vars.color.surfaceContainerHigh,
  surfaceContainerHighest: vars.color.surfaceContainerHighest,
  surfaceContainerLow: vars.color.surfaceContainerLow,
  surfaceContainerLowest: vars.color.surfaceContainerLowest,
  surfaceTint: vars.color.surfaceTint,
  surfaceVariant: vars.color.surfaceVariant,
  tertiary: vars.color.tertiary,
  tertiaryContainer: vars.color.tertiaryContainer,
  warning: vars.color.warning,
  warningContainer: vars.color.warningContainer,
};

const size = {
  auto: 'auto',
  full: '100%',
  screen: '100vw',
  screenHeight: '100vh',
  dynamicScreenHeight: '100dvh',
  min: 'min-content',
  max: 'max-content',
  fit: 'fit-content',
  legacyAccentBar: '3px',
  legacyDrawer: '28rem',
  legacyEpisodeSm: '160px',
  legacyEpisodeLg: '220px',
  legacyQuickCode: '5.5rem',
  ...vars.space,
};

const shadow = {
  ...vars.shadow,
  legacyPrimaryGlow8: '0 0 8px rgba(79, 70, 229, 0.4)',
  legacyPrimaryGlow30: '0 0 30px rgba(79, 70, 229, 0.2)',
  legacySecondaryGlow8: '0 0 8px rgba(129, 140, 248, 0.4)',
  legacySecondaryGlow10: '0 0 10px rgba(129, 140, 248, 0.55)',
  legacyErrorGlow8: '0 0 8px rgba(255, 107, 122, 0.4)',
};

const conditions = {
  base: {},
  sm: { '@media': `screen and (min-width: ${breakpoints.sm})` },
  md: { '@media': `screen and (min-width: ${breakpoints.md})` },
  lg: { '@media': `screen and (min-width: ${breakpoints.lg})` },
  xl: { '@media': `screen and (min-width: ${breakpoints.xl})` },
  '2xl': { '@media': `screen and (min-width: ${breakpoints['2xl']})` },
  hover: { selector: '&:hover' },
  focus: { selector: '&:focus' },
  active: { selector: '&:active' },
  disabled: { selector: '&:is(:disabled, [aria-disabled="true"], [data-disabled])' },
  dark: { selector: "[data-theme='dark'] &" },
};

const responsiveProperties = defineProperties({
  conditions,
  defaultCondition: 'base',
  responsiveArray: ['base', 'sm', 'md', 'lg', 'xl', '2xl'],
  properties: {
    display: {
      none: 'none',
      block: 'block',
      inline: 'inline',
      inlineBlock: 'inline-block',
      flex: 'flex',
      inlineFlex: 'inline-flex',
      grid: 'grid',
      contents: 'contents',
    },
    position: ['static', 'relative', 'absolute', 'fixed', 'sticky'],
    overflow: ['visible', 'hidden', 'clip', 'scroll', 'auto'],
    overflowX: ['visible', 'hidden', 'clip', 'scroll', 'auto'],
    overflowY: ['visible', 'hidden', 'clip', 'scroll', 'auto'],
    width: size,
    height: size,
    minWidth: size,
    minHeight: size,
    maxWidth: size,
    flexDirection: ['row', 'row-reverse', 'column', 'column-reverse'],
    flexWrap: ['nowrap', 'wrap', 'wrap-reverse'],
    flexShrink: {
      '0': 0,
      '1': 1,
    },
    flexGrow: {
      '0': 0,
      '1': 1,
    },
    alignItems: ['stretch', 'flex-start', 'center', 'flex-end', 'baseline'],
    justifyContent: [
      'normal',
      'flex-start',
      'center',
      'flex-end',
      'space-between',
      'space-around',
      'space-evenly',
    ],
    gap: vars.space,
    rowGap: vars.space,
    columnGap: vars.space,
    paddingTop: vars.space,
    paddingRight: vars.space,
    paddingBottom: vars.space,
    paddingLeft: vars.space,
    marginTop: { auto: 'auto', ...vars.space },
    marginRight: { auto: 'auto', ...vars.space },
    marginBottom: { auto: 'auto', ...vars.space },
    marginLeft: { auto: 'auto', ...vars.space },
    fontSize: vars.fontSize,
    fontWeight: vars.fontWeight,
    lineHeight: vars.lineHeight,
    textAlign: ['left', 'center', 'right', 'start', 'end'],
    color: colors,
    backgroundColor: colors,
    borderColor: colors,
    borderRadius: vars.borderRadius,
    boxShadow: shadow,
    opacity: {
      '0': '0',
      '50': '0.5',
      '60': '0.6',
      '70': '0.7',
      '80': '0.8',
      '90': '0.9',
      '100': '1',
    },
    zIndex: vars.zIndex,
  },
  shorthands: {
    p: ['paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft'],
    px: ['paddingLeft', 'paddingRight'],
    py: ['paddingTop', 'paddingBottom'],
    pt: ['paddingTop'],
    pr: ['paddingRight'],
    pb: ['paddingBottom'],
    pl: ['paddingLeft'],
    m: ['marginTop', 'marginRight', 'marginBottom', 'marginLeft'],
    mx: ['marginLeft', 'marginRight'],
    my: ['marginTop', 'marginBottom'],
    mt: ['marginTop'],
    mr: ['marginRight'],
    mb: ['marginBottom'],
    ml: ['marginLeft'],
    bg: ['backgroundColor'],
  },
});

export const sprinkles = createSprinkles(responsiveProperties);

export type Sprinkles = Parameters<typeof sprinkles>[0];
