/**
 * Canonical design-token literals for JellyPilot.
 * Consumed by panda.config.ts (value owner) and by tests.
 * Do not import this from application components.
 */

export const rawColors = {
  neutral: {
    '0': '#ffffff',
    '50': '#f3f6ff',
    '300': '#aeb8cc',
    '500': '#5c6c8c',
    '700': '#262e42',
    '750': '#22293e',
    '800': '#1e2538',
    '850': '#161b2a',
    '900': '#111420',
    '925': '#0b0d14',
    '950': '#0a0c12',
    '975': '#05060a',
    '1000': '#040508',
  },
  indigo: {
    '50': '#e0e2ff',
    '300': '#818cf8',
    '600': '#4f46e5',
    '900': '#1f2152',
    '950': '#1b1c3b',
    '1000': '#0b0a24',
  },
  teal: {
    '50': '#bfffe8',
    '400': '#4fe3b1',
    '900': '#06382a',
    '1000': '#001f16',
  },
  amber: {
    '50': '#ffe7a8',
    '400': '#f6c768',
    '900': '#3f2e08',
    '1000': '#2a1a00',
  },
  red: {
    '50': '#ffd9de',
    '400': '#ff6b7a',
    '900': '#4b1119',
    '1000': '#330006',
  },
  controlRoomLight: {
    canvas: '#f6f7ff',
    surfaceLowest: '#ffffff',
    surface: '#f1f3fc',
    surfaceContainer: '#e7ebf8',
    surfaceHigh: '#dce2f2',
    surfaceHighest: '#d4dbea',
    ink: '#101322',
    mutedInk: '#4b556f',
    line: '#8b95ad',
    lineSubtle: '#c5cce0',
    primary: '#4f46e5',
    onPrimary: '#ffffff',
    primaryContainer: '#e0e2ff',
    onPrimaryContainer: '#1b1c3b',
    secondary: '#4338ca',
    onSecondary: '#ffffff',
    secondaryContainer: '#e0e2ff',
    onSecondaryContainer: '#1f2152',
    success: '#0f766e',
    onSuccess: '#ffffff',
    successContainer: '#ccfbf1',
    onSuccessContainer: '#042f2e',
    successIndicator: '#14b8a6',
    info: '#1d4ed8',
    onInfo: '#ffffff',
    infoContainer: '#dbeafe',
    onInfoContainer: '#172554',
    infoIndicator: '#3b82f6',
    warning: '#b45309',
    onWarning: '#ffffff',
    warningContainer: '#ffedd5',
    onWarningContainer: '#431407',
    warningIndicator: '#f59e0b',
    error: '#b91c1c',
    onError: '#ffffff',
    errorContainer: '#fee2e2',
    onErrorContainer: '#450a0a',
    errorIndicator: '#ef4444',
    neutral: '#475569',
    onNeutral: '#ffffff',
    neutralContainer: '#e2e8f0',
    onNeutralContainer: '#0f172a',
    neutralIndicator: '#64748b',
    focusRing: '#4f46e5',
    key: '#ffffff',
    keyHover: '#f1f3fc',
    keyPressed: '#dce2f2',
  },
  braunLight: {
    canvas: '#fcf8f8',
    surface: '#f6f3f2',
    panel: '#ebe7e6',
    ink: '#1c1b1b',
    mutedInk: '#444846',
    line: '#c4c7c5',
    lineSubtle: 'rgb(28 27 27 / 0.12)',
    accent: '#c2410c',
    onAccent: '#ffffff',
    accentContainer: '#ffdbcc',
    onAccentContainer: '#3b1400',
    key: '#ffffff',
    keyAlt: '#f1edec',
    keyHover: '#f6f3f2',
    keyPressed: '#e3dfde',
    success: '#047857',
    onSuccess: '#ffffff',
    successContainer: '#d1fae5',
    onSuccessContainer: '#022c22',
    successIndicator: '#10b981',
    info: '#0e7490',
    onInfo: '#ffffff',
    infoContainer: '#cffafe',
    onInfoContainer: '#083344',
    infoIndicator: '#06b6d4',
    warning: '#92400e',
    onWarning: '#ffffff',
    warningContainer: '#ffedd5',
    onWarningContainer: '#431407',
    warningIndicator: '#f59e0b',
    error: '#b91c1c',
    onError: '#ffffff',
    errorContainer: '#fee2e2',
    onErrorContainer: '#450a0a',
    errorIndicator: '#dc2626',
    neutral: '#4b5563',
    onNeutral: '#ffffff',
    neutralContainer: '#e5e7eb',
    onNeutralContainer: '#111827',
    neutralIndicator: '#9ca3af',
    focusRing: '#c2410c',
  },
  braunDark: {
    canvas: '#0c0e12',
    surface: '#151821',
    panel: '#1a1d26',
    ink: '#f3f4f6',
    mutedInk: '#9ca3af',
    line: 'rgb(255 255 255 / 0.14)',
    lineSubtle: 'rgb(255 255 255 / 0.08)',
    accent: '#f97316',
    onAccent: '#1c0900',
    accentContainer: '#7c2d12',
    onAccentContainer: '#ffdbcc',
    key: '#2a2f3b',
    keyAlt: '#353b48',
    keyHover: '#353b48',
    keyPressed: '#1f2430',
    success: '#34d399',
    onSuccess: '#022c22',
    successContainer: '#064e3b',
    onSuccessContainer: '#a7f3d0',
    successIndicator: '#10b981',
    info: '#22d3ee',
    onInfo: '#083344',
    infoContainer: '#155e75',
    onInfoContainer: '#a5f3fc',
    infoIndicator: '#06b6d4',
    warning: '#fbbf24',
    onWarning: '#422006',
    warningContainer: '#78350f',
    onWarningContainer: '#fde68a',
    warningIndicator: '#f59e0b',
    error: '#f87171',
    onError: '#450a0a',
    errorContainer: '#7f1d1d',
    onErrorContainer: '#fecaca',
    errorIndicator: '#ef4444',
    neutral: '#d1d5db',
    onNeutral: '#111827',
    neutralContainer: '#374151',
    onNeutralContainer: '#f3f4f6',
    neutralIndicator: '#9ca3af',
    focusRing: '#fb923c',
  },
} as const;

/** Semantic roles → raw palette path (Panda token reference) for Control Room Dark base. */
export const semanticColorRefs = {
  background: 'colors.neutral.975',
  error: 'colors.red.400',
  errorContainer: 'colors.red.900',
  onBackground: 'colors.neutral.50',
  onError: 'colors.red.1000',
  onErrorContainer: 'colors.red.50',
  errorIndicator: 'colors.red.400',
  onPrimary: 'colors.neutral.0',
  onPrimaryContainer: 'colors.indigo.50',
  onSecondary: 'colors.indigo.1000',
  onSecondaryContainer: 'colors.indigo.50',
  onSurface: 'colors.neutral.50',
  onSurfaceVariant: 'colors.neutral.300',
  onTertiary: 'colors.teal.1000',
  onTertiaryContainer: 'colors.teal.50',
  onWarning: 'colors.amber.1000',
  onWarningContainer: 'colors.amber.50',
  outline: 'colors.neutral.500',
  outlineVariant: 'colors.neutral.700',
  primary: 'colors.indigo.600',
  primaryContainer: 'colors.indigo.950',
  secondary: 'colors.indigo.300',
  secondaryContainer: 'colors.indigo.900',
  surface: 'colors.neutral.925',
  surfaceContainer: 'colors.neutral.900',
  surfaceContainerHigh: 'colors.neutral.850',
  surfaceContainerHighest: 'colors.neutral.750',
  surfaceContainerLow: 'colors.neutral.950',
  surfaceContainerLowest: 'colors.neutral.1000',
  surfaceTint: 'colors.indigo.600',
  surfaceVariant: 'colors.neutral.800',
  tertiary: 'colors.teal.400',
  tertiaryContainer: 'colors.teal.900',
  warning: 'colors.amber.400',
  warningContainer: 'colors.amber.900',
  warningIndicator: 'colors.amber.400',
  success: 'colors.teal.400',
  onSuccess: 'colors.teal.1000',
  successContainer: 'colors.teal.900',
  onSuccessContainer: 'colors.teal.50',
  successIndicator: 'colors.teal.400',
  info: 'colors.indigo.300',
  onInfo: 'colors.indigo.1000',
  infoContainer: 'colors.indigo.900',
  onInfoContainer: 'colors.indigo.50',
  infoIndicator: 'colors.indigo.300',
  neutral: 'colors.neutral.300',
  onNeutral: 'colors.neutral.975',
  neutralContainer: 'colors.neutral.800',
  onNeutralContainer: 'colors.neutral.50',
  neutralIndicator: 'colors.neutral.300',
  focusRing: 'colors.indigo.300',
  artworkOutline: 'colors.neutral.0',
  artworkShadow: 'colors.neutral.1000',
  materialSurfaceRaised: 'colors.neutral.900',
  materialSurfaceRecessed: 'colors.neutral.950',
  materialSurfaceAcrylic: 'colors.neutral.900',
  materialSurfaceGlass: 'colors.neutral.850',
  materialSurfaceKey: 'colors.neutral.850',
  materialSurfaceKeyHover: 'colors.neutral.800',
  materialSurfacePressed: 'colors.neutral.750',
  materialEdgeSubtle: 'colors.neutral.700',
  materialEdgeNormal: 'colors.neutral.500',
  materialEdgeStrong: 'colors.neutral.300',
  materialEdgeSpecular: 'colors.neutral.50',
  materialDepthAmbient: 'colors.neutral.1000',
  materialDepthRaised: 'colors.neutral.1000',
  materialDepthRecessed: 'colors.neutral.1000',
  materialDepthOverlay: 'colors.neutral.1000',
  materialDepthKeycap: 'colors.neutral.1000',
  materialDepthPressed: 'colors.neutral.1000',
  materialDepthIndicator: 'colors.teal.400',
} as const;

export const semanticColorHex = {
  background: rawColors.neutral['975'],
  error: rawColors.red['400'],
  errorContainer: rawColors.red['900'],
  errorIndicator: rawColors.red['400'],
  onBackground: rawColors.neutral['50'],
  onError: rawColors.red['1000'],
  onErrorContainer: rawColors.red['50'],
  onPrimary: rawColors.neutral['0'],
  onPrimaryContainer: rawColors.indigo['50'],
  onSecondary: rawColors.indigo['1000'],
  onSecondaryContainer: rawColors.indigo['50'],
  onSurface: rawColors.neutral['50'],
  onSurfaceVariant: rawColors.neutral['300'],
  onTertiary: rawColors.teal['1000'],
  onTertiaryContainer: rawColors.teal['50'],
  onWarning: rawColors.amber['1000'],
  onWarningContainer: rawColors.amber['50'],
  outline: rawColors.neutral['500'],
  outlineVariant: rawColors.neutral['700'],
  primary: rawColors.indigo['600'],
  primaryContainer: rawColors.indigo['950'],
  secondary: rawColors.indigo['300'],
  secondaryContainer: rawColors.indigo['900'],
  surface: rawColors.neutral['925'],
  surfaceContainer: rawColors.neutral['900'],
  surfaceContainerHigh: rawColors.neutral['850'],
  surfaceContainerHighest: rawColors.neutral['750'],
  surfaceContainerLow: rawColors.neutral['950'],
  surfaceContainerLowest: rawColors.neutral['1000'],
  surfaceTint: rawColors.indigo['600'],
  surfaceVariant: rawColors.neutral['800'],
  tertiary: rawColors.teal['400'],
  tertiaryContainer: rawColors.teal['900'],
  warning: rawColors.amber['400'],
  warningContainer: rawColors.amber['900'],
  warningIndicator: rawColors.amber['400'],
  success: rawColors.teal['400'],
  onSuccess: rawColors.teal['1000'],
  successContainer: rawColors.teal['900'],
  onSuccessContainer: rawColors.teal['50'],
  successIndicator: rawColors.teal['400'],
  info: rawColors.indigo['300'],
  onInfo: rawColors.indigo['1000'],
  infoContainer: rawColors.indigo['900'],
  onInfoContainer: rawColors.indigo['50'],
  infoIndicator: rawColors.indigo['300'],
  neutral: rawColors.neutral['300'],
  onNeutral: rawColors.neutral['975'],
  neutralContainer: rawColors.neutral['800'],
  onNeutralContainer: rawColors.neutral['50'],
  neutralIndicator: rawColors.neutral['300'],
  focusRing: rawColors.indigo['300'],
  artworkOutline: rawColors.neutral['0'],
  artworkShadow: rawColors.neutral['1000'],
  materialSurfaceRaised: rawColors.neutral['900'],
  materialSurfaceRecessed: rawColors.neutral['950'],
  materialSurfaceAcrylic: rawColors.neutral['900'],
  materialSurfaceGlass: rawColors.neutral['850'],
  materialSurfaceKey: rawColors.neutral['850'],
  materialSurfaceKeyHover: rawColors.neutral['800'],
  materialSurfacePressed: rawColors.neutral['750'],
  materialEdgeSubtle: rawColors.neutral['700'],
  materialEdgeNormal: rawColors.neutral['500'],
  materialEdgeStrong: rawColors.neutral['300'],
  materialEdgeSpecular: rawColors.neutral['50'],
  materialDepthAmbient: rawColors.neutral['1000'],
  materialDepthRaised: rawColors.neutral['1000'],
  materialDepthRecessed: rawColors.neutral['1000'],
  materialDepthOverlay: rawColors.neutral['1000'],
  materialDepthKeycap: rawColors.neutral['1000'],
  materialDepthPressed: rawColors.neutral['1000'],
  materialDepthIndicator: rawColors.teal['400'],
} as const;

export type SemanticColorRole = keyof typeof semanticColorHex;

const controlRoomLightSemantic = {
  background: rawColors.controlRoomLight.canvas,
  onBackground: rawColors.controlRoomLight.ink,
  surface: rawColors.controlRoomLight.surface,
  surfaceContainer: rawColors.controlRoomLight.surfaceContainer,
  surfaceContainerHigh: rawColors.controlRoomLight.surfaceHigh,
  surfaceContainerHighest: rawColors.controlRoomLight.surfaceHighest,
  surfaceContainerLow: rawColors.controlRoomLight.surface,
  surfaceContainerLowest: rawColors.controlRoomLight.surfaceLowest,
  surfaceVariant: rawColors.controlRoomLight.surfaceHigh,
  surfaceTint: rawColors.controlRoomLight.primary,
  onSurface: rawColors.controlRoomLight.ink,
  onSurfaceVariant: rawColors.controlRoomLight.mutedInk,
  outline: rawColors.controlRoomLight.line,
  outlineVariant: rawColors.controlRoomLight.lineSubtle,
  primary: rawColors.controlRoomLight.primary,
  onPrimary: rawColors.controlRoomLight.onPrimary,
  primaryContainer: rawColors.controlRoomLight.primaryContainer,
  onPrimaryContainer: rawColors.controlRoomLight.onPrimaryContainer,
  secondary: rawColors.controlRoomLight.secondary,
  onSecondary: rawColors.controlRoomLight.onSecondary,
  secondaryContainer: rawColors.controlRoomLight.secondaryContainer,
  onSecondaryContainer: rawColors.controlRoomLight.onSecondaryContainer,
  tertiary: rawColors.controlRoomLight.success,
  onTertiary: rawColors.controlRoomLight.onSuccess,
  tertiaryContainer: rawColors.controlRoomLight.successContainer,
  onTertiaryContainer: rawColors.controlRoomLight.onSuccessContainer,
  warning: rawColors.controlRoomLight.warning,
  onWarning: rawColors.controlRoomLight.onWarning,
  warningContainer: rawColors.controlRoomLight.warningContainer,
  onWarningContainer: rawColors.controlRoomLight.onWarningContainer,
  warningIndicator: rawColors.controlRoomLight.warning,
  error: rawColors.controlRoomLight.error,
  onError: rawColors.controlRoomLight.onError,
  errorContainer: rawColors.controlRoomLight.errorContainer,
  onErrorContainer: rawColors.controlRoomLight.onErrorContainer,
  errorIndicator: rawColors.controlRoomLight.error,
  success: rawColors.controlRoomLight.success,
  onSuccess: rawColors.controlRoomLight.onSuccess,
  successContainer: rawColors.controlRoomLight.successContainer,
  onSuccessContainer: rawColors.controlRoomLight.onSuccessContainer,
  successIndicator: rawColors.controlRoomLight.success,
  info: rawColors.controlRoomLight.info,
  onInfo: rawColors.controlRoomLight.onInfo,
  infoContainer: rawColors.controlRoomLight.infoContainer,
  onInfoContainer: rawColors.controlRoomLight.onInfoContainer,
  infoIndicator: rawColors.controlRoomLight.info,
  neutral: rawColors.controlRoomLight.neutral,
  onNeutral: rawColors.controlRoomLight.onNeutral,
  neutralContainer: rawColors.controlRoomLight.neutralContainer,
  onNeutralContainer: rawColors.controlRoomLight.onNeutralContainer,
  neutralIndicator: rawColors.controlRoomLight.neutral,
  focusRing: rawColors.controlRoomLight.focusRing,
  artworkOutline: '#000000',
  artworkShadow: 'rgb(16 19 34 / 0.28)',
  materialSurfaceRaised: rawColors.controlRoomLight.surfaceLowest,
  materialSurfaceRecessed: rawColors.controlRoomLight.surface,
  materialSurfaceAcrylic: 'rgb(255 255 255 / 0.72)',
  materialSurfaceGlass: 'rgb(246 247 255 / 0.78)',
  materialSurfaceKey: rawColors.controlRoomLight.key,
  materialSurfaceKeyHover: rawColors.controlRoomLight.keyHover,
  materialSurfacePressed: rawColors.controlRoomLight.keyPressed,
  materialEdgeSubtle: rawColors.controlRoomLight.lineSubtle,
  materialEdgeNormal: rawColors.controlRoomLight.line,
  materialEdgeStrong: rawColors.controlRoomLight.mutedInk,
  materialEdgeSpecular: rawColors.controlRoomLight.surfaceLowest,
  materialDepthAmbient: 'rgb(16 19 34 / 0.08)',
  materialDepthRaised: 'rgb(16 19 34 / 0.12)',
  materialDepthRecessed: 'rgb(16 19 34 / 0.1)',
  materialDepthOverlay: 'rgb(16 19 34 / 0.18)',
  materialDepthKeycap: 'rgb(16 19 34 / 0.14)',
  materialDepthPressed: 'rgb(16 19 34 / 0.2)',
  materialDepthIndicator: rawColors.controlRoomLight.successIndicator,
} as const satisfies Record<SemanticColorRole, string>;

const braunLightSemantic = {
  background: rawColors.braunLight.canvas,
  onBackground: rawColors.braunLight.ink,
  surface: rawColors.braunLight.surface,
  surfaceContainer: rawColors.braunLight.panel,
  surfaceContainerHigh: rawColors.braunLight.keyAlt,
  surfaceContainerHighest: rawColors.braunLight.line,
  surfaceContainerLow: rawColors.braunLight.surface,
  surfaceContainerLowest: rawColors.braunLight.key,
  surfaceVariant: rawColors.braunLight.panel,
  surfaceTint: rawColors.braunLight.accent,
  onSurface: rawColors.braunLight.ink,
  onSurfaceVariant: rawColors.braunLight.mutedInk,
  outline: rawColors.braunLight.line,
  outlineVariant: rawColors.braunLight.lineSubtle,
  primary: rawColors.braunLight.accent,
  onPrimary: rawColors.braunLight.onAccent,
  primaryContainer: rawColors.braunLight.accentContainer,
  onPrimaryContainer: rawColors.braunLight.onAccentContainer,
  secondary: rawColors.braunLight.mutedInk,
  onSecondary: rawColors.braunLight.key,
  secondaryContainer: rawColors.braunLight.panel,
  onSecondaryContainer: rawColors.braunLight.ink,
  tertiary: rawColors.braunLight.success,
  onTertiary: rawColors.braunLight.onSuccess,
  tertiaryContainer: rawColors.braunLight.successContainer,
  onTertiaryContainer: rawColors.braunLight.onSuccessContainer,
  warning: rawColors.braunLight.warning,
  onWarning: rawColors.braunLight.onWarning,
  warningContainer: rawColors.braunLight.warningContainer,
  onWarningContainer: rawColors.braunLight.onWarningContainer,
  warningIndicator: rawColors.braunLight.warning,
  error: rawColors.braunLight.error,
  onError: rawColors.braunLight.onError,
  errorContainer: rawColors.braunLight.errorContainer,
  onErrorContainer: rawColors.braunLight.onErrorContainer,
  errorIndicator: rawColors.braunLight.error,
  success: rawColors.braunLight.success,
  onSuccess: rawColors.braunLight.onSuccess,
  successContainer: rawColors.braunLight.successContainer,
  onSuccessContainer: rawColors.braunLight.onSuccessContainer,
  successIndicator: rawColors.braunLight.success,
  info: rawColors.braunLight.info,
  onInfo: rawColors.braunLight.onInfo,
  infoContainer: rawColors.braunLight.infoContainer,
  onInfoContainer: rawColors.braunLight.onInfoContainer,
  infoIndicator: rawColors.braunLight.info,
  neutral: rawColors.braunLight.neutral,
  onNeutral: rawColors.braunLight.onNeutral,
  neutralContainer: rawColors.braunLight.neutralContainer,
  onNeutralContainer: rawColors.braunLight.onNeutralContainer,
  neutralIndicator: rawColors.braunLight.neutral,
  focusRing: rawColors.braunLight.focusRing,
  artworkOutline: '#000000',
  artworkShadow: 'rgb(28 27 27 / 0.24)',
  materialSurfaceRaised: rawColors.braunLight.surface,
  materialSurfaceRecessed: rawColors.braunLight.panel,
  materialSurfaceAcrylic: 'rgb(246 243 242 / 0.82)',
  materialSurfaceGlass: 'rgb(252 248 248 / 0.72)',
  materialSurfaceKey: rawColors.braunLight.key,
  materialSurfaceKeyHover: rawColors.braunLight.keyHover,
  materialSurfacePressed: rawColors.braunLight.keyPressed,
  materialEdgeSubtle: rawColors.braunLight.lineSubtle,
  materialEdgeNormal: rawColors.braunLight.line,
  materialEdgeStrong: rawColors.braunLight.mutedInk,
  materialEdgeSpecular: rawColors.braunLight.key,
  materialDepthAmbient: 'rgb(28 27 27 / 0.1)',
  materialDepthRaised: 'rgb(28 27 27 / 0.14)',
  materialDepthRecessed: 'rgb(28 27 27 / 0.12)',
  materialDepthOverlay: 'rgb(28 27 27 / 0.2)',
  materialDepthKeycap: 'rgb(28 27 27 / 0.16)',
  materialDepthPressed: 'rgb(28 27 27 / 0.22)',
  materialDepthIndicator: rawColors.braunLight.successIndicator,
} as const satisfies Record<SemanticColorRole, string>;

const braunDarkSemantic = {
  background: rawColors.braunDark.canvas,
  onBackground: rawColors.braunDark.ink,
  surface: rawColors.braunDark.surface,
  surfaceContainer: rawColors.braunDark.panel,
  surfaceContainerHigh: rawColors.braunDark.key,
  surfaceContainerHighest: rawColors.braunDark.keyAlt,
  surfaceContainerLow: rawColors.braunDark.surface,
  surfaceContainerLowest: '#080a0e',
  surfaceVariant: rawColors.braunDark.panel,
  surfaceTint: rawColors.braunDark.accent,
  onSurface: rawColors.braunDark.ink,
  onSurfaceVariant: rawColors.braunDark.mutedInk,
  outline: rawColors.braunDark.line,
  outlineVariant: rawColors.braunDark.lineSubtle,
  primary: rawColors.braunDark.accent,
  onPrimary: rawColors.braunDark.onAccent,
  primaryContainer: rawColors.braunDark.accentContainer,
  onPrimaryContainer: rawColors.braunDark.onAccentContainer,
  secondary: rawColors.braunDark.mutedInk,
  onSecondary: rawColors.braunDark.canvas,
  secondaryContainer: rawColors.braunDark.key,
  onSecondaryContainer: rawColors.braunDark.ink,
  tertiary: rawColors.braunDark.success,
  onTertiary: rawColors.braunDark.onSuccess,
  tertiaryContainer: rawColors.braunDark.successContainer,
  onTertiaryContainer: rawColors.braunDark.onSuccessContainer,
  warning: rawColors.braunDark.warning,
  onWarning: rawColors.braunDark.onWarning,
  warningContainer: rawColors.braunDark.warningContainer,
  onWarningContainer: rawColors.braunDark.onWarningContainer,
  warningIndicator: rawColors.braunDark.warning,
  error: rawColors.braunDark.error,
  onError: rawColors.braunDark.onError,
  errorContainer: rawColors.braunDark.errorContainer,
  onErrorContainer: rawColors.braunDark.onErrorContainer,
  errorIndicator: rawColors.braunDark.error,
  success: rawColors.braunDark.success,
  onSuccess: rawColors.braunDark.onSuccess,
  successContainer: rawColors.braunDark.successContainer,
  onSuccessContainer: rawColors.braunDark.onSuccessContainer,
  successIndicator: rawColors.braunDark.success,
  info: rawColors.braunDark.info,
  onInfo: rawColors.braunDark.onInfo,
  infoContainer: rawColors.braunDark.infoContainer,
  onInfoContainer: rawColors.braunDark.onInfoContainer,
  infoIndicator: rawColors.braunDark.info,
  neutral: rawColors.braunDark.neutral,
  onNeutral: rawColors.braunDark.onNeutral,
  neutralContainer: rawColors.braunDark.neutralContainer,
  onNeutralContainer: rawColors.braunDark.onNeutralContainer,
  neutralIndicator: rawColors.braunDark.neutral,
  focusRing: rawColors.braunDark.focusRing,
  artworkOutline: '#ffffff',
  artworkShadow: 'rgb(0 0 0 / 0.45)',
  materialSurfaceRaised: rawColors.braunDark.panel,
  materialSurfaceRecessed: rawColors.braunDark.surface,
  materialSurfaceAcrylic: 'rgb(26 29 38 / 0.86)',
  materialSurfaceGlass: 'rgb(12 14 18 / 0.72)',
  materialSurfaceKey: rawColors.braunDark.key,
  materialSurfaceKeyHover: rawColors.braunDark.keyHover,
  materialSurfacePressed: rawColors.braunDark.keyPressed,
  materialEdgeSubtle: rawColors.braunDark.lineSubtle,
  materialEdgeNormal: rawColors.braunDark.line,
  materialEdgeStrong: rawColors.braunDark.mutedInk,
  materialEdgeSpecular: 'rgb(255 255 255 / 0.22)',
  materialDepthAmbient: 'rgb(0 0 0 / 0.35)',
  materialDepthRaised: 'rgb(0 0 0 / 0.4)',
  materialDepthRecessed: 'rgb(0 0 0 / 0.45)',
  materialDepthOverlay: 'rgb(0 0 0 / 0.5)',
  materialDepthKeycap: 'rgb(0 0 0 / 0.42)',
  materialDepthPressed: 'rgb(0 0 0 / 0.55)',
  materialDepthIndicator: rawColors.braunDark.successIndicator,
} as const satisfies Record<SemanticColorRole, string>;

export const appearanceSemanticColors = {
  'control-room': {
    dark: semanticColorHex,
    light: controlRoomLightSemantic,
  },
  braun: {
    dark: braunDarkSemantic,
    light: braunLightSemantic,
  },
} as const;

export const requiredSemanticColorRoles = Object.keys(semanticColorHex) as SemanticColorRole[];

export const fonts = {
  display: "'Space Grotesk Variable', 'Inter Variable', ui-sans-serif, system-ui, sans-serif",
  mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  sans: "'Inter Variable', ui-sans-serif, system-ui, sans-serif",
  body: "'Inter Variable', ui-sans-serif, system-ui, sans-serif",
  readout: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
} as const;

export const braunFonts = {
  display: "'Archivo Variable', 'Inter Variable', ui-sans-serif, system-ui, sans-serif",
  mono: "'JetBrains Mono Variable', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  sans: "'Archivo Variable', 'Inter Variable', ui-sans-serif, system-ui, sans-serif",
  body: "'Archivo Variable', 'Inter Variable', ui-sans-serif, system-ui, sans-serif",
  readout:
    "'JetBrains Mono Variable', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
} as const;

export const spacing = {
  '0': '0',
  px: '1px',
  '0_5': '0.125rem',
  '1': '0.25rem',
  '1_5': '0.375rem',
  '2': '0.5rem',
  '2_5': '0.625rem',
  '3': '0.75rem',
  '3_5': '0.875rem',
  '4': '1rem',
  '5': '1.25rem',
  '6': '1.5rem',
  '7': '1.75rem',
  '8': '2rem',
  '9': '2.25rem',
  '10': '2.5rem',
  '11': '2.75rem',
  '12': '3rem',
  '14': '3.5rem',
  '16': '4rem',
  '20': '5rem',
  '24': '6rem',
  xs: '0.75rem',
  sm: '0.875rem',
  md: '1rem',
  lg: '1.125rem',
  xl: '1.25rem',
  '2xl': '1.5rem',
  '3xl': '1.875rem',
  '4xl': '2.25rem',
  '5xl': '3rem',
  '6xl': '3.75rem',
  '7xl': '4.5rem',
  '8xl': '6rem',
  '9xl': '8rem',
} as const;

export const fontSizes = {
  '10': '0.625rem',
  '11': '0.6875rem',
  '12': '0.75rem',
  '13': '0.8125rem',
  '14': '0.875rem',
  '15': '0.9375rem',
  '16': '1rem',
  '18': '1.125rem',
  '20': '1.25rem',
  '22': '1.375rem',
  '24': '1.5rem',
  '28': '1.75rem',
  '32': '2rem',
  '36': '2.25rem',
  '45': '2.8125rem',
} as const;

export const lineHeights = {
  none: '1',
  tight: '1.25',
  snug: '1.375',
  normal: '1.5',
  relaxed: '1.625',
  loose: '2',
  '14': '0.875rem',
  '16': '1rem',
  '20': '1.25rem',
  '22': '1.375rem',
  '24': '1.5rem',
  '28': '1.75rem',
  '32': '2rem',
  '40': '2.5rem',
  '44': '2.75rem',
  '52': '3.25rem',
} as const;

export const fontWeights = {
  normal: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
  extrabold: '800',
  black: '900',
} as const;

export const radii = {
  none: '0',
  sm: '0.125rem',
  md: '0.375rem',
  lg: '0.5rem',
  xl: '0.75rem',
  '2xl': '1rem',
  '3xl': '1.5rem',
  '4xl': '2rem',
  full: '9999px',
  panel: '1rem',
  control: '0.75rem',
  overlay: '1.25rem',
  artwork: '0.75rem',
  indicator: '9999px',
} as const;

export const braunRadii = {
  none: '0',
  sm: '0.125rem',
  md: '0.25rem',
  lg: '0.375rem',
  xl: '0.5rem',
  '2xl': '0.75rem',
  '3xl': '1rem',
  '4xl': '1.25rem',
  full: '9999px',
  panel: '0.5rem',
  control: '0.375rem',
  overlay: '0.75rem',
  artwork: '0.375rem',
  indicator: '9999px',
} as const;

export const shadows = {
  none: '0 0 rgb(0 0 0 / 0)',
  sm: '0 1px 2px 0 rgb(0 0 0 / 0.2)',
  md: '0 4px 8px -2px rgb(0 0 0 / 0.35)',
  lg: '0 10px 18px -6px rgb(0 0 0 / 0.45)',
  xl: '0 18px 30px -10px rgb(0 0 0 / 0.55)',
  '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.65)',
  inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.28)',
} as const;

export const zIndex = {
  auto: 'auto',
  '0': '0',
  '10': '10',
  '20': '20',
  '40': '40',
  '50': '50',
  '60': '60',
  '100': '100',
  behind: '-1',
} as const;

export const letterSpacings = {
  '0': '0',
  '5': '0.05em',
  '8': '0.08em',
  '18': '0.18em',
  '20': '0.2em',
  '25': '0.25em',
} as const;

export const durations = {
  none: '0s',
  '75': '75ms',
  '100': '100ms',
  '150': '150ms',
  '200': '200ms',
  '300': '300ms',
  '500': '500ms',
  '700': '700ms',
  '1000': '1000ms',
  interaction: '150ms',
  overlay: '200ms',
  appearance: '200ms',
  mechanical: '120ms',
} as const;

export const easings = {
  standard: 'cubic-bezier(0.2, 0, 0, 1)',
  emphasized: 'cubic-bezier(0.16, 1, 0.3, 1)',
  inOut: 'cubic-bezier(0.4, 0, 0.6, 1)',
  linear: 'linear',
} as const;

/** Compile-time breakpoints for Panda responsive conditions. */
export const breakpoints = {
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px',
} as const;

export const controlRoomDarkCanvasHex = semanticColorHex.background;
export const controlRoomLightCanvasHex = controlRoomLightSemantic.background;
export const braunLightCanvasHex = braunLightSemantic.background;
export const braunDarkCanvasHex = braunDarkSemantic.background;
