import { createGlobalTheme, createGlobalThemeContract } from '@vanilla-extract/css';

/**
 * JMSR design-token source.
 *
 * This is the single owner of design token values. Tailwind utilities consume
 * these tokens via `@theme inline` aliases in `src/index.css`; component-local
 * vanilla-extract CSS consumes them directly through `vars.*`.
 */
export const vars = createGlobalThemeContract({
  color: {
    background: '--jmsr-color-background',
    brandGlow: '--jmsr-color-brand-glow',
    error: '--jmsr-color-error',
    errorContainer: '--jmsr-color-error-container',
    onBackground: '--jmsr-color-on-background',
    onError: '--jmsr-color-on-error',
    onErrorContainer: '--jmsr-color-on-error-container',
    onPrimary: '--jmsr-color-on-primary',
    onPrimaryContainer: '--jmsr-color-on-primary-container',
    onSecondary: '--jmsr-color-on-secondary',
    onSecondaryContainer: '--jmsr-color-on-secondary-container',
    onSurface: '--jmsr-color-on-surface',
    onSurfaceVariant: '--jmsr-color-on-surface-variant',
    onTertiary: '--jmsr-color-on-tertiary',
    onTertiaryContainer: '--jmsr-color-on-tertiary-container',
    onWarning: '--jmsr-color-on-warning',
    onWarningContainer: '--jmsr-color-on-warning-container',
    outline: '--jmsr-color-outline',
    outlineVariant: '--jmsr-color-outline-variant',
    primary: '--jmsr-color-primary',
    primaryContainer: '--jmsr-color-primary-container',
    primaryGradientEnd: '--jmsr-color-primary-gradient-end',
    secondary: '--jmsr-color-secondary',
    secondaryContainer: '--jmsr-color-secondary-container',
    secondaryGradientEnd: '--jmsr-color-secondary-gradient-end',
    surface: '--jmsr-color-surface',
    surfaceContainer: '--jmsr-color-surface-container',
    surfaceContainerHigh: '--jmsr-color-surface-container-high',
    surfaceContainerHighest: '--jmsr-color-surface-container-highest',
    surfaceContainerLow: '--jmsr-color-surface-container-low',
    surfaceContainerLowest: '--jmsr-color-surface-container-lowest',
    surfaceTint: '--jmsr-color-surface-tint',
    surfaceVariant: '--jmsr-color-surface-variant',
    tertiary: '--jmsr-color-tertiary',
    tertiaryContainer: '--jmsr-color-tertiary-container',
    warning: '--jmsr-color-warning',
    warningContainer: '--jmsr-color-warning-container',
  },
  font: {
    display: '--jmsr-font-display',
    mono: '--jmsr-font-mono',
    sans: '--jmsr-font-sans',
  },
});

createGlobalTheme(':root', vars, {
  color: {
    background: '#05060a',
    brandGlow: '#4f46e5',
    error: '#ff6b7a',
    errorContainer: '#4b1119',
    onBackground: '#f3f6ff',
    onError: '#330006',
    onErrorContainer: '#ffd9de',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#e0e2ff',
    onSecondary: '#0b0a24',
    onSecondaryContainer: '#e0e2ff',
    onSurface: '#f3f6ff',
    onSurfaceVariant: '#aeb8cc',
    onTertiary: '#001f16',
    onTertiaryContainer: '#bfffe8',
    onWarning: '#2a1a00',
    onWarningContainer: '#ffe7a8',
    outline: '#5c6c8c',
    outlineVariant: '#262e42',
    primary: '#4f46e5',
    primaryContainer: '#1b1c3b',
    primaryGradientEnd: '#7a7eff',
    secondary: '#818cf8',
    secondaryContainer: '#1f2152',
    secondaryGradientEnd: '#0b4b60',
    surface: '#0b0d14',
    surfaceContainer: '#111420',
    surfaceContainerHigh: '#161b2a',
    surfaceContainerHighest: '#22293e',
    surfaceContainerLow: '#0a0c12',
    surfaceContainerLowest: '#040508',
    surfaceTint: '#4f46e5',
    surfaceVariant: '#1e2538',
    tertiary: '#4fe3b1',
    tertiaryContainer: '#06382a',
    warning: '#f6c768',
    warningContainer: '#3f2e08',
  },
  font: {
    display: "'Space Grotesk Variable', 'Inter Variable', ui-sans-serif, system-ui, sans-serif",
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    sans: "'Inter Variable', ui-sans-serif, system-ui, sans-serif",
  },
});
