import {
  borderRadius as miniBorderRadius,
  breakpoints as miniBreakpoints,
  duration as miniDuration,
  fontSize as miniFontSize,
  fontWeight as miniFontWeight,
  lineHeight as miniLineHeight,
  spacing as miniSpacing,
} from '@unocss/preset-mini/theme';
import { createGlobalTheme, createGlobalThemeContract } from '@vanilla-extract/css';

const unoSpacing = miniSpacing as Record<string, string>;
const unoFontSize = miniFontSize as Record<string, readonly [string, string]>;
const unoFontWeight = miniFontWeight as Record<string, string>;
const unoLineHeight = miniLineHeight as Record<string, string>;
const unoBorderRadius = miniBorderRadius as Record<string, string>;
const unoDuration = miniDuration as Record<string, string>;
const unoBreakpoints = miniBreakpoints as Record<string, string>;

const spaceValue = {
  '0': unoSpacing.none,
  px: '1px',
  '0_5': '0.125rem',
  '1': '0.25rem',
  '1_5': '0.375rem',
  '2': '0.5rem',
  '2_5': '0.625rem',
  '3': '0.75rem',
  '3_5': '0.875rem',
  '4': '1rem',
  '5': '1.25rem',
  '6': '1.5rem',
  '7': '1.75rem',
  '8': '2rem',
  '9': '2.25rem',
  '10': '2.5rem',
  '11': '2.75rem',
  '12': '3rem',
  '14': '3.5rem',
  '16': '4rem',
  '20': '5rem',
  '24': '6rem',
  xs: unoSpacing.xs,
  sm: unoSpacing.sm,
  md: unoSpacing.DEFAULT,
  lg: unoSpacing.lg,
  xl: unoSpacing.xl,
  '2xl': unoSpacing['2xl'],
  '3xl': unoSpacing['3xl'],
  '4xl': unoSpacing['4xl'],
  '5xl': unoSpacing['5xl'],
  '6xl': unoSpacing['6xl'],
  '7xl': unoSpacing['7xl'],
  '8xl': unoSpacing['8xl'],
  '9xl': unoSpacing['9xl'],
};

const fontSizeValue = {
  '10': '0.625rem',
  '11': '0.6875rem',
  '12': unoFontSize.xs[0],
  '13': '0.8125rem',
  '14': unoFontSize.sm[0],
  '15': '0.9375rem',
  '16': unoFontSize.base[0],
  '18': unoFontSize.lg[0],
  '20': unoFontSize.xl[0],
  '22': '1.375rem',
  '24': unoFontSize['2xl'][0],
  '28': '1.75rem',
  '32': '2rem',
  '36': unoFontSize['4xl'][0],
  '45': '2.8125rem',
};

const lineHeightValue = {
  none: unoLineHeight.none,
  tight: unoLineHeight.tight,
  snug: unoLineHeight.snug,
  normal: unoLineHeight.normal,
  relaxed: unoLineHeight.relaxed,
  loose: unoLineHeight.loose,
  '14': '0.875rem',
  '16': '1rem',
  '20': '1.25rem',
  '22': '1.375rem',
  '24': '1.5rem',
  '28': '1.75rem',
  '32': '2rem',
  '40': '2.5rem',
  '44': '2.75rem',
  '52': '3.25rem',
};

const fontWeightValue = {
  normal: unoFontWeight.normal,
  medium: unoFontWeight.medium,
  semibold: unoFontWeight.semibold,
  bold: unoFontWeight.bold,
  extrabold: unoFontWeight.extrabold,
  black: unoFontWeight.black,
};

const borderRadiusValue = {
  none: unoBorderRadius.none,
  sm: unoBorderRadius.sm,
  md: unoBorderRadius.md,
  lg: unoBorderRadius.lg,
  xl: unoBorderRadius.xl,
  '2xl': unoBorderRadius['2xl'],
  '3xl': unoBorderRadius['3xl'],
  '4xl': '2rem',
  full: unoBorderRadius.full,
};

const shadowValue = {
  none: '0 0 rgb(0 0 0 / 0)',
  sm: '0 1px 2px 0 rgb(15 23 42 / 0.08)',
  md: '0 8px 18px -12px rgb(15 23 42 / 0.18)',
  lg: '0 16px 32px -18px rgb(15 23 42 / 0.24)',
  xl: '0 24px 44px -24px rgb(15 23 42 / 0.28)',
  '2xl': '0 32px 60px -30px rgb(15 23 42 / 0.34)',
  inner: 'inset 0 1px 2px 0 rgb(15 23 42 / 0.12)',
};

const zIndexValue = {
  auto: 'auto',
  '0': '0',
  '10': '10',
  '40': '40',
  '50': '50',
  '60': '60',
  '100': '100',
};

const durationValue = {
  none: unoDuration.none,
  '75': unoDuration['75'],
  '100': unoDuration['100'],
  '150': unoDuration['150'],
  '200': unoDuration['200'],
  '300': unoDuration['300'],
  '500': unoDuration['500'],
  '700': unoDuration['700'],
  '1000': unoDuration['1000'],
};

const easingValue = {
  standard: 'cubic-bezier(0.2, 0, 0, 1)',
  emphasized: 'cubic-bezier(0.16, 1, 0.3, 1)',
  linear: 'linear',
};

const sizeValue = {
  controlXs: '1.75rem',
  controlSm: '2rem',
  controlMd: '2.5rem',
  controlLg: '3rem',
  iconSm: '1rem',
  iconMd: '1.25rem',
  iconLg: '1.5rem',
  sidebar: '16rem',
  drawer: '28rem',
};

const typeScaleValue = {
  displaySize: '2.75rem',
  displayLineHeight: '3.25rem',
  headlineSize: '2rem',
  headlineLineHeight: '2.5rem',
  titleSize: '1.25rem',
  titleLineHeight: '1.75rem',
  bodySize: '0.875rem',
  bodyLineHeight: '1.25rem',
  labelSize: '0.75rem',
  labelLineHeight: '1rem',
};

const motionValue = {
  durationInstant: '0ms',
  durationFast: '120ms',
  durationNormal: '180ms',
  durationSlow: '260ms',
  easingStandard: easingValue.standard,
  easingEmphasized: easingValue.emphasized,
};

const breakpointValue = {
  sm: unoBreakpoints.sm,
  md: unoBreakpoints.md,
  lg: unoBreakpoints.lg,
  xl: unoBreakpoints.xl,
  '2xl': unoBreakpoints['2xl'],
};

export const breakpoints = breakpointValue;

const tokenContract = <Token extends string>(group: string, values: Record<Token, string>) =>
  Object.fromEntries(
    Object.keys(values).map((key) => [key, `--jellypilot-${group}-${key.replaceAll('_', '-')}`]),
  ) as Record<Token, string>;

/**
 * JellyPilot design-token source.
 *
 * This is the single owner of design token values. Sprinkles, Recipes,
 * global styles, and component-local vanilla-extract CSS consume them directly
 * through `vars.*`.
 */
export const vars = createGlobalThemeContract({
  background: {
    app: '--jellypilot-background-app',
    page: '--jellypilot-background-page',
    panel: '--jellypilot-background-panel',
    raised: '--jellypilot-background-raised',
    inset: '--jellypilot-background-inset',
    overlay: '--jellypilot-background-overlay',
    scrim: '--jellypilot-background-scrim',
  },
  color: {
    background: '--jellypilot-color-background',
    brandGlow: '--jellypilot-color-brand-glow',
    error: '--jellypilot-color-error',
    errorContainer: '--jellypilot-color-error-container',
    onBackground: '--jellypilot-color-on-background',
    onError: '--jellypilot-color-on-error',
    onErrorContainer: '--jellypilot-color-on-error-container',
    onPrimary: '--jellypilot-color-on-primary',
    onPrimaryContainer: '--jellypilot-color-on-primary-container',
    onSecondary: '--jellypilot-color-on-secondary',
    onSecondaryContainer: '--jellypilot-color-on-secondary-container',
    onSurface: '--jellypilot-color-on-surface',
    onSurfaceVariant: '--jellypilot-color-on-surface-variant',
    onTertiary: '--jellypilot-color-on-tertiary',
    onTertiaryContainer: '--jellypilot-color-on-tertiary-container',
    onWarning: '--jellypilot-color-on-warning',
    onWarningContainer: '--jellypilot-color-on-warning-container',
    outline: '--jellypilot-color-outline',
    outlineVariant: '--jellypilot-color-outline-variant',
    primary: '--jellypilot-color-primary',
    primaryContainer: '--jellypilot-color-primary-container',
    primaryGradientEnd: '--jellypilot-color-primary-gradient-end',
    secondary: '--jellypilot-color-secondary',
    secondaryContainer: '--jellypilot-color-secondary-container',
    secondaryGradientEnd: '--jellypilot-color-secondary-gradient-end',
    surface: '--jellypilot-color-surface',
    surfaceContainer: '--jellypilot-color-surface-container',
    surfaceContainerHigh: '--jellypilot-color-surface-container-high',
    surfaceContainerHighest: '--jellypilot-color-surface-container-highest',
    surfaceContainerLow: '--jellypilot-color-surface-container-low',
    surfaceContainerLowest: '--jellypilot-color-surface-container-lowest',
    surfaceTint: '--jellypilot-color-surface-tint',
    surfaceVariant: '--jellypilot-color-surface-variant',
    tertiary: '--jellypilot-color-tertiary',
    tertiaryContainer: '--jellypilot-color-tertiary-container',
    warning: '--jellypilot-color-warning',
    warningContainer: '--jellypilot-color-warning-container',
  },
  text: {
    primary: '--jellypilot-text-primary',
    secondary: '--jellypilot-text-secondary',
    muted: '--jellypilot-text-muted',
    inverse: '--jellypilot-text-inverse',
    accent: '--jellypilot-text-accent',
    success: '--jellypilot-text-success',
    warning: '--jellypilot-text-warning',
    danger: '--jellypilot-text-danger',
  },
  icon: {
    primary: '--jellypilot-icon-primary',
    secondary: '--jellypilot-icon-secondary',
    muted: '--jellypilot-icon-muted',
    accent: '--jellypilot-icon-accent',
    success: '--jellypilot-icon-success',
    warning: '--jellypilot-icon-warning',
    danger: '--jellypilot-icon-danger',
  },
  border: {
    subtle: '--jellypilot-border-subtle',
    default: '--jellypilot-border-default',
    strong: '--jellypilot-border-strong',
    focus: '--jellypilot-border-focus',
    success: '--jellypilot-border-success',
    warning: '--jellypilot-border-warning',
    danger: '--jellypilot-border-danger',
  },
  accent: {
    primary: {
      bg: '--jellypilot-accent-primary-bg',
      bgHover: '--jellypilot-accent-primary-bg-hover',
      bgPressed: '--jellypilot-accent-primary-bg-pressed',
      text: '--jellypilot-accent-primary-text',
      subtle: '--jellypilot-accent-primary-subtle',
      border: '--jellypilot-accent-primary-border',
    },
    secondary: {
      bg: '--jellypilot-accent-secondary-bg',
      bgHover: '--jellypilot-accent-secondary-bg-hover',
      bgPressed: '--jellypilot-accent-secondary-bg-pressed',
      text: '--jellypilot-accent-secondary-text',
      subtle: '--jellypilot-accent-secondary-subtle',
      border: '--jellypilot-accent-secondary-border',
    },
  },
  status: {
    success: {
      bg: '--jellypilot-status-success-bg',
      text: '--jellypilot-status-success-text',
      border: '--jellypilot-status-success-border',
    },
    warning: {
      bg: '--jellypilot-status-warning-bg',
      text: '--jellypilot-status-warning-text',
      border: '--jellypilot-status-warning-border',
    },
    danger: {
      bg: '--jellypilot-status-danger-bg',
      text: '--jellypilot-status-danger-text',
      border: '--jellypilot-status-danger-border',
    },
    info: {
      bg: '--jellypilot-status-info-bg',
      text: '--jellypilot-status-info-text',
      border: '--jellypilot-status-info-border',
    },
  },
  data: {
    blue: '--jellypilot-data-blue',
    cyan: '--jellypilot-data-cyan',
    green: '--jellypilot-data-green',
    amber: '--jellypilot-data-amber',
    red: '--jellypilot-data-red',
    purple: '--jellypilot-data-purple',
  },
  font: {
    display: '--jellypilot-font-display',
    mono: '--jellypilot-font-mono',
    sans: '--jellypilot-font-sans',
  },
  space: tokenContract('space', spaceValue),
  size: tokenContract('size', sizeValue),
  fontSize: tokenContract('font-size', fontSizeValue),
  fontWeight: tokenContract('font-weight', fontWeightValue),
  lineHeight: tokenContract('line-height', lineHeightValue),
  typeScale: tokenContract('type-scale', typeScaleValue),
  radius: tokenContract('radius-semantic', borderRadiusValue),
  borderRadius: tokenContract('radius', borderRadiusValue),
  shadow: tokenContract('shadow', shadowValue),
  zIndex: tokenContract('z-index', zIndexValue),
  duration: tokenContract('duration', durationValue),
  easing: tokenContract('easing', easingValue),
  motion: tokenContract('motion', motionValue),
  breakpoint: tokenContract('breakpoint', breakpointValue),
});

createGlobalTheme(':root', vars, {
  background: {
    app: '#f4f7fb',
    page: '#ffffff',
    panel: '#ffffff',
    raised: '#f8fafc',
    inset: '#eef3f8',
    overlay: '#ffffff',
    scrim: 'rgb(15 23 42 / 0.42)',
  },
  color: {
    background: '#f4f7fb',
    brandGlow: '#4f46e5',
    error: '#dc2626',
    errorContainer: '#fee2e2',
    onBackground: '#0f172a',
    onError: '#ffffff',
    onErrorContainer: '#7f1d1d',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#312e81',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#155e75',
    onSurface: '#0f172a',
    onSurfaceVariant: '#64748b',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#166534',
    onWarning: '#422006',
    onWarningContainer: '#92400e',
    outline: '#94a3b8',
    outlineVariant: '#d8e0eb',
    primary: '#4f46e5',
    primaryContainer: '#e0e7ff',
    primaryGradientEnd: '#6366f1',
    secondary: '#0891b2',
    secondaryContainer: '#cffafe',
    secondaryGradientEnd: '#0e7490',
    surface: '#ffffff',
    surfaceContainer: '#f8fafc',
    surfaceContainerHigh: '#eef3f8',
    surfaceContainerHighest: '#e2e8f0',
    surfaceContainerLow: '#ffffff',
    surfaceContainerLowest: '#ffffff',
    surfaceTint: '#4f46e5',
    surfaceVariant: '#e2e8f0',
    tertiary: '#16a34a',
    tertiaryContainer: '#dcfce7',
    warning: '#f59e0b',
    warningContainer: '#fef3c7',
  },
  text: {
    primary: '#0f172a',
    secondary: '#475569',
    muted: '#64748b',
    inverse: '#f8fafc',
    accent: '#4338ca',
    success: '#166534',
    warning: '#92400e',
    danger: '#b91c1c',
  },
  icon: {
    primary: '#334155',
    secondary: '#64748b',
    muted: '#94a3b8',
    accent: '#4f46e5',
    success: '#16a34a',
    warning: '#d97706',
    danger: '#dc2626',
  },
  border: {
    subtle: '#e5edf5',
    default: '#d8e0eb',
    strong: '#94a3b8',
    focus: '#4f46e5',
    success: '#86efac',
    warning: '#facc15',
    danger: '#fca5a5',
  },
  accent: {
    primary: {
      bg: '#4f46e5',
      bgHover: '#4338ca',
      bgPressed: '#3730a3',
      text: '#ffffff',
      subtle: '#eef2ff',
      border: '#c7d2fe',
    },
    secondary: {
      bg: '#0891b2',
      bgHover: '#0e7490',
      bgPressed: '#155e75',
      text: '#ffffff',
      subtle: '#ecfeff',
      border: '#a5f3fc',
    },
  },
  status: {
    success: {
      bg: '#dcfce7',
      text: '#166534',
      border: '#86efac',
    },
    warning: {
      bg: '#fef3c7',
      text: '#92400e',
      border: '#facc15',
    },
    danger: {
      bg: '#fee2e2',
      text: '#b91c1c',
      border: '#fca5a5',
    },
    info: {
      bg: '#dbeafe',
      text: '#1d4ed8',
      border: '#93c5fd',
    },
  },
  data: {
    blue: '#2563eb',
    cyan: '#0891b2',
    green: '#16a34a',
    amber: '#d97706',
    red: '#dc2626',
    purple: '#7c3aed',
  },
  font: {
    display: "'Figtree Variable', ui-sans-serif, system-ui, sans-serif",
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    sans: "'Figtree Variable', ui-sans-serif, system-ui, sans-serif",
  },
  space: spaceValue,
  size: sizeValue,
  fontSize: fontSizeValue,
  fontWeight: fontWeightValue,
  lineHeight: lineHeightValue,
  typeScale: typeScaleValue,
  radius: borderRadiusValue,
  borderRadius: borderRadiusValue,
  shadow: shadowValue,
  zIndex: zIndexValue,
  duration: durationValue,
  easing: easingValue,
  motion: motionValue,
  breakpoint: breakpointValue,
});

createGlobalTheme("[data-theme='dark']", vars, {
  background: {
    app: '#05060a',
    page: '#0b0d14',
    panel: '#111420',
    raised: '#161b2a',
    inset: '#0a0c12',
    overlay: '#161b2a',
    scrim: 'rgb(0 0 0 / 0.58)',
  },
  color: {
    background: '#05060a',
    brandGlow: '#4f46e5',
    error: '#ff6b7a',
    errorContainer: '#4b1119',
    onBackground: '#f3f6ff',
    onError: '#330006',
    onErrorContainer: '#ffd9de',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#e0e2ff',
    onSecondary: '#0b0a24',
    onSecondaryContainer: '#e0e2ff',
    onSurface: '#f3f6ff',
    onSurfaceVariant: '#aeb8cc',
    onTertiary: '#001f16',
    onTertiaryContainer: '#bfffe8',
    onWarning: '#2a1a00',
    onWarningContainer: '#ffe7a8',
    outline: '#5c6c8c',
    outlineVariant: '#262e42',
    primary: '#4f46e5',
    primaryContainer: '#1b1c3b',
    primaryGradientEnd: '#7a7eff',
    secondary: '#818cf8',
    secondaryContainer: '#1f2152',
    secondaryGradientEnd: '#0b4b60',
    surface: '#0b0d14',
    surfaceContainer: '#111420',
    surfaceContainerHigh: '#161b2a',
    surfaceContainerHighest: '#22293e',
    surfaceContainerLow: '#0a0c12',
    surfaceContainerLowest: '#040508',
    surfaceTint: '#4f46e5',
    surfaceVariant: '#1e2538',
    tertiary: '#4fe3b1',
    tertiaryContainer: '#06382a',
    warning: '#f6c768',
    warningContainer: '#3f2e08',
  },
  text: {
    primary: '#f3f6ff',
    secondary: '#c8d2e6',
    muted: '#aeb8cc',
    inverse: '#0f172a',
    accent: '#a5b4fc',
    success: '#86efac',
    warning: '#fde68a',
    danger: '#fda4af',
  },
  icon: {
    primary: '#e2e8f0',
    secondary: '#aeb8cc',
    muted: '#74819b',
    accent: '#a5b4fc',
    success: '#86efac',
    warning: '#f6c768',
    danger: '#ff6b7a',
  },
  border: {
    subtle: '#262e42',
    default: '#33415f',
    strong: '#5c6c8c',
    focus: '#818cf8',
    success: '#167857',
    warning: '#a66a12',
    danger: '#9f2433',
  },
  accent: {
    primary: {
      bg: '#4f46e5',
      bgHover: '#6366f1',
      bgPressed: '#4338ca',
      text: '#ffffff',
      subtle: '#1b1c3b',
      border: '#4f46e5',
    },
    secondary: {
      bg: '#4fe3b1',
      bgHover: '#6ff0c2',
      bgPressed: '#36c99a',
      text: '#001f16',
      subtle: '#06382a',
      border: '#167857',
    },
  },
  status: {
    success: {
      bg: '#06382a',
      text: '#bfffe8',
      border: '#167857',
    },
    warning: {
      bg: '#3f2e08',
      text: '#ffe7a8',
      border: '#a66a12',
    },
    danger: {
      bg: '#4b1119',
      text: '#ffd9de',
      border: '#9f2433',
    },
    info: {
      bg: '#1b1c3b',
      text: '#e0e2ff',
      border: '#4f46e5',
    },
  },
  data: {
    blue: '#60a5fa',
    cyan: '#67e8f9',
    green: '#86efac',
    amber: '#fbbf24',
    red: '#f87171',
    purple: '#c4b5fd',
  },
  font: {
    display: "'Figtree Variable', ui-sans-serif, system-ui, sans-serif",
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    sans: "'Figtree Variable', ui-sans-serif, system-ui, sans-serif",
  },
  space: spaceValue,
  size: sizeValue,
  fontSize: fontSizeValue,
  fontWeight: fontWeightValue,
  lineHeight: lineHeightValue,
  typeScale: typeScaleValue,
  radius: borderRadiusValue,
  borderRadius: borderRadiusValue,
  shadow: shadowValue,
  zIndex: zIndexValue,
  duration: durationValue,
  easing: easingValue,
  motion: motionValue,
  breakpoint: breakpointValue,
});
