/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsPlayerRouteImport } from './routes/settings/player'
import { Route as SettingsLogsRouteImport } from './routes/settings/logs'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings/keybindings'
import { Route as SettingsDeviceRouteImport } from './routes/settings/device'
import { Route as SettingsActionsRouteImport } from './routes/settings/actions'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPlayerRoute = SettingsPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDeviceRoute = SettingsDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsActionsRoute = SettingsActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/actions': typeof SettingsActionsRoute
  '/settings/device': typeof SettingsDeviceRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/player': typeof SettingsPlayerRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings/actions': typeof SettingsActionsRoute
  '/settings/device': typeof SettingsDeviceRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/player': typeof SettingsPlayerRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/actions': typeof SettingsActionsRoute
  '/settings/device': typeof SettingsDeviceRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/player': typeof SettingsPlayerRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/settings/actions'
    | '/settings/device'
    | '/settings/keybindings'
    | '/settings/logs'
    | '/settings/player'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings/actions'
    | '/settings/device'
    | '/settings/keybindings'
    | '/settings/logs'
    | '/settings/player'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/settings/actions'
    | '/settings/device'
    | '/settings/keybindings'
    | '/settings/logs'
    | '/settings/player'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/player': {
      id: '/settings/player'
      path: '/player'
      fullPath: '/settings/player'
      preLoaderRoute: typeof SettingsPlayerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logs': {
      id: '/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SettingsLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/device': {
      id: '/settings/device'
      path: '/device'
      fullPath: '/settings/device'
      preLoaderRoute: typeof SettingsDeviceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/actions': {
      id: '/settings/actions'
      path: '/actions'
      fullPath: '/settings/actions'
      preLoaderRoute: typeof SettingsActionsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsActionsRoute: typeof SettingsActionsRoute
  SettingsDeviceRoute: typeof SettingsDeviceRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsLogsRoute: typeof SettingsLogsRoute
  SettingsPlayerRoute: typeof SettingsPlayerRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsActionsRoute: SettingsActionsRoute,
  SettingsDeviceRoute: SettingsDeviceRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsPlayerRoute: SettingsPlayerRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
