/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library/index'
import { Route as AuthenticatedLibraryShowsSeriesIdRouteImport } from './routes/_authenticated/library/shows/$seriesId'
import { Route as AuthenticatedLibraryItemsItemIdRouteImport } from './routes/_authenticated/library/items/$itemId'
import { Route as AuthenticatedLibraryCollectionTypeLibraryIdRouteImport } from './routes/_authenticated/library/$collectionType/$libraryId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryShowsSeriesIdRoute =
  AuthenticatedLibraryShowsSeriesIdRouteImport.update({
    id: '/shows/$seriesId',
    path: '/shows/$seriesId',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryItemsItemIdRoute =
  AuthenticatedLibraryItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryCollectionTypeLibraryIdRoute =
  AuthenticatedLibraryCollectionTypeLibraryIdRouteImport.update({
    id: '/$collectionType/$libraryId',
    path: '/$collectionType/$libraryId',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/library/$collectionType/$libraryId': typeof AuthenticatedLibraryCollectionTypeLibraryIdRoute
  '/library/items/$itemId': typeof AuthenticatedLibraryItemsItemIdRoute
  '/library/shows/$seriesId': typeof AuthenticatedLibraryShowsSeriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/library/$collectionType/$libraryId': typeof AuthenticatedLibraryCollectionTypeLibraryIdRoute
  '/library/items/$itemId': typeof AuthenticatedLibraryItemsItemIdRoute
  '/library/shows/$seriesId': typeof AuthenticatedLibraryShowsSeriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/library/$collectionType/$libraryId': typeof AuthenticatedLibraryCollectionTypeLibraryIdRoute
  '/_authenticated/library/items/$itemId': typeof AuthenticatedLibraryItemsItemIdRoute
  '/_authenticated/library/shows/$seriesId': typeof AuthenticatedLibraryShowsSeriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/library'
    | '/library/'
    | '/library/$collectionType/$libraryId'
    | '/library/items/$itemId'
    | '/library/shows/$seriesId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/library'
    | '/library/$collectionType/$libraryId'
    | '/library/items/$itemId'
    | '/library/shows/$seriesId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/library'
    | '/_authenticated/library/'
    | '/_authenticated/library/$collectionType/$libraryId'
    | '/_authenticated/library/items/$itemId'
    | '/_authenticated/library/shows/$seriesId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/shows/$seriesId': {
      id: '/_authenticated/library/shows/$seriesId'
      path: '/shows/$seriesId'
      fullPath: '/library/shows/$seriesId'
      preLoaderRoute: typeof AuthenticatedLibraryShowsSeriesIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/items/$itemId': {
      id: '/_authenticated/library/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/library/items/$itemId'
      preLoaderRoute: typeof AuthenticatedLibraryItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/$collectionType/$libraryId': {
      id: '/_authenticated/library/$collectionType/$libraryId'
      path: '/$collectionType/$libraryId'
      fullPath: '/library/$collectionType/$libraryId'
      preLoaderRoute: typeof AuthenticatedLibraryCollectionTypeLibraryIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
  }
}

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
  AuthenticatedLibraryCollectionTypeLibraryIdRoute: typeof AuthenticatedLibraryCollectionTypeLibraryIdRoute
  AuthenticatedLibraryItemsItemIdRoute: typeof AuthenticatedLibraryItemsItemIdRoute
  AuthenticatedLibraryShowsSeriesIdRoute: typeof AuthenticatedLibraryShowsSeriesIdRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
  AuthenticatedLibraryCollectionTypeLibraryIdRoute:
    AuthenticatedLibraryCollectionTypeLibraryIdRoute,
  AuthenticatedLibraryItemsItemIdRoute: AuthenticatedLibraryItemsItemIdRoute,
  AuthenticatedLibraryShowsSeriesIdRoute:
    AuthenticatedLibraryShowsSeriesIdRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
