[package]
name = "jellypilot-local-video"
version = "0.1.0"
edition = "2021"
rust-version = "1.98"
license = "MIT"
publish = false
workspace = "../../crates/jellypilot-player"

[dependencies]
iced = { git = "https://github.com/hewel/iced.git", rev = "f812ae504989444eb57d9f8669c1ab5a2e326c95", features = ["advanced", "advanced-shaping", "image", "svg", "tokio"] }
jellypilot-player = { path = "../../crates/jellypilot-player" }
jellypilot-ui = { path = "../../crates/jellypilot-ui" }
tokio = { version = "1.50.0", features = ["time"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
